name: Despliegue

on:
  push:
    branches:
      - dev
      - main

env:
  AWS_REGION: 'us-east-2'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: clone_repository
        uses: actions/checkout@v3

      - name: install_terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.9.6'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: 'us-east-2'
      
      - name: terraform init
        run: |
          terraform init
  
      - name: select_workspace
        run: |
          bash ./scripts/set_environment.sh "${{ github.ref }}" >> $GITHUB_ENV
          echo $GITHUB_ENV
          terraform workspace select -or-create $GITHUB_ENV

      - name: terraform_plan
        run: |
          terraform plan -var-file $GITHUB_ENV.tfvars -auto-aprove